//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using UnityEngine;

namespace TreeSharpPlus
{
	public class IfThenElse : NodeGroup
	{
		private Node ifNode, thenNode, elseNode;
		public IfThenElse (Node ifNode, Node thenNode, Node elseNode)
		{
			this.ifNode = ifNode;
			this.thenNode = thenNode;
			this.elseNode = elseNode;
		}

		public override IEnumerable<RunStatus> Execute()
		{
			RunStatus ifStatus = this.TickNode (ifNode);
			while (ifStatus == RunStatus.Running) {
				yield return RunStatus.Running;
				ifStatus = this.TickNode(ifNode);
			}

			if (ifStatus == RunStatus.Success) {
				RunStatus thenStatus = this.TickNode(thenNode);
				while (thenStatus == RunStatus.Running) {
					yield return RunStatus.Running;
					thenStatus = this.TickNode(thenNode);
				}
			} else {
				RunStatus elseStatus = this.TickNode(elseNode);
				while (elseStatus == RunStatus.Running) {
					yield return RunStatus.Running;
					elseStatus = this.TickNode(elseNode);
				}
			}
			yield return RunStatus.Success;
			yield break;
		}
	}
}
